# Basic environment for summary stats
name: summarystats_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - cartopy
  - scipy
  - pandas
  - netcdf4
  - xarray
  - dask
  - pytest
  - matplotlib
  - pyproj
  - pip:
    - arm-pyart
    - act-atmos
