name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - cartopy
  - scipy
  - pandas
  - netcdf4
  - xarray
  - dask
  - pytest
  - ipython
  - matplotlib
  - pyproj
  - pip
  - pip:
    - arm-pyart
    - act-atmos
